/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * Definitions for constants used in the device's SDP database.
 *
 */

// exjobb_dualmode_sdp_db.h

#ifndef __SDP_DATABASE_H__
#define __SDP_DATABASE_H__

// SDP Record for GATT (Generic Attribute)
#define HDLR_GATT_GENERIC_ATTRIBUTE 0x10001
// SDP Record for GATT (Generic Access)
#define HDLR_GATT_GENERIC_ACCESS    0x10002
// SDP Record for Serial Port
#define HDLR_SERIAL_PORT            0x10003
#define SERIAL_PORT_SCN             0x01

// External definitions
extern const uint8_t  sdp_database[];
extern const uint16_t sdp_database_len;

#endif /* __SDP_DATABASE_H__ */
