/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * BLE device's GATT database and device configuration.
 *
 */

// exjobb_dualmode_db.c

#include "wiced_bt_uuid.h"
#include "wiced_bt_gatt.h"
#include "exjobb_dualmode_db.h"

/*************************************************************************************
** GATT server definitions
*************************************************************************************/

const uint8_t gatt_database[] = // Define GATT database
{
    /* Primary Service 'Generic Attribute' */
    PRIMARY_SERVICE_UUID16 (HDLS_GENERIC_ATTRIBUTE, UUID_SERVICE_GATT),

    /* Primary Service 'Generic Access' */
    PRIMARY_SERVICE_UUID16 (HDLS_GENERIC_ACCESS, UUID_SERVICE_GAP),

        /* Characteristic 'Device Name' */
        CHARACTERISTIC_UUID16 (HDLC_GENERIC_ACCESS_DEVICE_NAME, HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE,
            UUID_CHARACTERISTIC_DEVICE_NAME, LEGATTDB_CHAR_PROP_READ,
            LEGATTDB_PERM_READABLE),

        /* Characteristic 'Appearance' */
        CHARACTERISTIC_UUID16 (HDLC_GENERIC_ACCESS_APPEARANCE, HDLC_GENERIC_ACCESS_APPEARANCE_VALUE,
            UUID_CHARACTERISTIC_APPEARANCE, LEGATTDB_CHAR_PROP_READ,
            LEGATTDB_PERM_READABLE),

    /* Primary Service 'Custom Serial GATT' */
    PRIMARY_SERVICE_UUID128 (HDLS_CUSTOM_SERIAL_GATT, __UUID_CUSTOM_SERIAL_GATT),

        /* Characteristic 'RX' */
        CHARACTERISTIC_UUID128 (HDLC_CUSTOM_SERIAL_GATT_RX, HDLC_CUSTOM_SERIAL_GATT_RX_VALUE,
            __UUID_CUSTOM_SERIAL_GATT_RX, LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_NOTIFY,
            LEGATTDB_PERM_READABLE),

            /* Descriptor 'Characteristic User Description' */
            CHAR_DESCRIPTOR_UUID16 (HDLD_CUSTOM_SERIAL_GATT_RX_USER_DESCRIPTION,
                UUID_DESCRIPTOR_CHARACTERISTIC_USER_DESCRIPTION, LEGATTDB_PERM_READABLE),

            /* Descriptor 'Client Characteristic Configuration' */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_CUSTOM_SERIAL_GATT_RX_CLIENT_CONFIGURATION,
                UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_AUTH_WRITABLE),

        /* Characteristic 'TX' */
        CHARACTERISTIC_UUID128_WRITABLE (HDLC_CUSTOM_SERIAL_GATT_TX, HDLC_CUSTOM_SERIAL_GATT_TX_VALUE,
            __UUID_CUSTOM_SERIAL_GATT_TX, LEGATTDB_CHAR_PROP_WRITE,
            LEGATTDB_PERM_WRITE_REQ),

            /* Descriptor 'Characteristic User Description' */
            CHAR_DESCRIPTOR_UUID16 (HDLD_CUSTOM_SERIAL_GATT_TX_USER_DESCRIPTION,
                UUID_DESCRIPTOR_CHARACTERISTIC_USER_DESCRIPTION, LEGATTDB_PERM_READABLE),

};

// Length of the GATT database
const uint16_t gatt_database_len = sizeof(gatt_database);

