/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * SDP database for Single Mode BR/EDR or Dual Mode device.
 *
 */

// exjobb_dualmode_sdp_db.c

#include "wiced_bt_uuid.h"
#include "wiced_bt_sdp.h"
#include "exjobb_dualmode_db.h"
#include "exjobb_dualmode_sdp_db.h"

const uint8_t sdp_database[] = // Define SDP database
{
    SDP_ATTR_SEQUENCE_1(185),

    // SDP Record for GATT (Generic Attribute)
    SDP_ATTR_SEQUENCE_1(48),
        SDP_ATTR_RECORD_HANDLE(HDLR_GATT_GENERIC_ATTRIBUTE),
        SDP_ATTR_CLASS_ID(UUID_SERVICE_GATT),
        SDP_ATTR_ID(ATTR_ID_PROTOCOL_DESC_LIST), SDP_ATTR_SEQUENCE_1(19),
            SDP_ATTR_SEQUENCE_1(6),
                SDP_ATTR_UUID16(UUID_PROTOCOL_L2CAP),
                SDP_ATTR_VALUE_UINT2(BT_PSM_ATT),
            SDP_ATTR_SEQUENCE_1(9),
                SDP_ATTR_UUID16(UUID_PROTOCOL_ATT),
                SDP_ATTR_VALUE_UINT2(HDLS_GENERIC_ATTRIBUTE),
                SDP_ATTR_VALUE_UINT2(HDLS_GENERIC_ATTRIBUTE),
        SDP_ATTR_BROWSE_LIST,

    // SDP Record for GATT (Generic Access)
    SDP_ATTR_SEQUENCE_1(48),
        SDP_ATTR_RECORD_HANDLE(HDLR_GATT_GENERIC_ACCESS),
        SDP_ATTR_CLASS_ID(UUID_SERVICE_GAP),
        SDP_ATTR_ID(ATTR_ID_PROTOCOL_DESC_LIST), SDP_ATTR_SEQUENCE_1(19),
            SDP_ATTR_SEQUENCE_1(6),
                SDP_ATTR_UUID16(UUID_PROTOCOL_L2CAP),
                SDP_ATTR_VALUE_UINT2(BT_PSM_ATT),
            SDP_ATTR_SEQUENCE_1(9),
                SDP_ATTR_UUID16(UUID_PROTOCOL_ATT),
                SDP_ATTR_VALUE_UINT2(HDLS_GENERIC_ACCESS),
                SDP_ATTR_VALUE_UINT2(HDLC_GENERIC_ACCESS_APPEARANCE_VALUE),
        SDP_ATTR_BROWSE_LIST,

    // SDP Record for Serial Port
    SDP_ATTR_SEQUENCE_1(83),
        SDP_ATTR_RECORD_HANDLE(HDLR_SERIAL_PORT),
        SDP_ATTR_CLASS_ID(UUID_SERVCLASS_SERIAL_PORT),
        SDP_ATTR_RFCOMM_PROTOCOL_DESC_LIST(SERIAL_PORT_SCN),
        SDP_ATTR_LANGUAGE_BASE_ATTR_ID_LIST,
        SDP_ATTR_PROFILE_DESC_LIST(UUID_SERVCLASS_SERIAL_PORT, 0x0102),
        SDP_ATTR_SERVICE_NAME(18),
            'B', 'R', '/', 'E', 'D', 'R', ' ', 'S', 'e', 'r', 'i', 'a', 'l', ' ', 'P', 'o', 'r', 't',

};

// Length of the SDP database
const uint16_t sdp_database_len = sizeof(sdp_database);
