#
# This file has been automatically generated by the WICED 20719-B1 Designer.
#

APP_SRC = exjobb_dualmode.c
APP_SRC += exjobb_dualmode_db.c
APP_SRC += exjobb_dualmode_sdp_db.c
APP_SRC += wiced_bt_cfg.c

########################################################################
# Component(s) needed
########################################################################
$(NAME)_COMPONENTS := spp_lib.a
########################################################################
# C flags
########################################################################
C_FLAGS += -DWICED_BT_TRACE_ENABLE

# If defined, HCI traces are sent over transport/WICED HCI interface
C_FLAGS += -DHCI_TRACE_OVER_TRANSPORT

########################################################################
################ DO NOT MODIFY FILE BELOW THIS LINE ####################
########################################################################

